sudo: false
language: ruby
cache: bundler
rvm:
  - '2.2.2'
before_script:
  - cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - bundle exec rake db:setup
addons:
  postgresql: '9.3'
