NewsTematica::Clases.newsletter_helper_extern = 'NewsletterHelper'
NewsTematica::Clases.tematica_extern = 'Tematica'
NewsTematica::Clases.contenido_extern = 'Contenido'
NewsTematica::Clases.antifail_extern = 'Antifail'
NewsTematica::Clases.tagging_extern = 'Tagging'
